### ISSUE TITLE
Quotes are not recognized in the keyword

### ISSUE THREAD

**Issue by Xebtria** [Nekolike/Mappy#4] opened 2020-01-19 08:30 UTC
https://i.imgur.com/x3njLf2.png
results in 
https://i.imgur.com/ICIRBpT.png

but with quotes you get different (= more strict) highlighting, so it would be appreciated if this would be supported.

**Comment by Nekolike** [comment] 2020-01-19 13:39
That is indeed something I have to look into! The function which reads from the file apparently removes single quotation marks by default, another user also reported this issue so I will have to find a way around that. As a solution for now, you can add another quotation mark next to the existing ones (like: ""item socket"") and give the script a reload in order to add the marks to the button!

**Comment by Nekolike** [comment] 2020-01-19 18:16
The problem seems to be solved, update will come soon! I would appreciate confirmation after the update on wether the problem is really solved.

I will close this issue for now, you are free to create a new one if the error occurs again!

**Closed as completed** 2020-01-20 02:46 UTC

**Comment by Xebtria** [comment] 2020-01-20 06:44
Can confirm, problem is solved, it works now! thanks :)
